#pragma once

// Experiment order:
// (MAX_DIFFERENCE_SUM 10, SIMULATE_NOISY_DISTANCE_SENSORS false)
// (MAX_DIFFERENCE_SUM 10, SIMULATE_NOISY_DISTANCE_SENSORS true)
// (MAX_DIFFERENCE_SUM 30, SIMULATE_NOISY_DISTANCE_SENSORS true)
// fewer sensors

#define MAX_DIFFERENCE_SUM 10
#define SIMULATE_NOISY_DISTANCE_SENSORS false
#define RESIZE_BELIEF_MAP_VISU false