all:
	rm -f imitation_learning
	clear
	@echo "Let us build the project imitation_learning"
	g++ -Wall *.cpp \
	    -o imitation_learning \
		`pkg-config --cflags --libs opencv4`
	@echo CODE COMPILED SUCCESSFULLY!